# NumPy 

NumPy est une puissante bibliothèque d'algèbres linéaires pour Python. Ce qui le rend si important, c'est que presque toutes les bibliothèques de l'écosystème <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) s'appuient sur NumPy comme l'un de leurs principaux éléments de construction. De plus, nous l'utiliserons pour générer des données pour nos exemples d'analyse plus tard !

NumPy est également incroyablement rapide, car il possède des relations avec les bibliothèques du langage C. Pour plus d'informations sur les raisons pour lesquelles vous souhaitez utiliser des tableaux plutôt que des listes, consultez ce [post StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Nous n'apprendrons que les bases de NumPy. Pour commencer, nous devons l'installer !

**Note : Instructions d'installation**

NumPy est déjà inclus dans votre environnement ! Nous recommandons VIVEMENT d'utiliser notre environnement comme indiqué dans la vidéo de mise en place de l'environnement. Vous pouvez continuer si vous utilisez l'environnement du cours !

_____
Pour ceux qui n'utilisent pas l'environnement de code recommandé :

**Il est fortement recommandé d'installer Python à l'aide de la distribution Anaconda pour vous assurer que toutes les dépendances sous-jacentes (telles que les bibliothèques d'algèbre linéaire) sont synchronisées avec l'utilisation d'une installation de conda. Si vous avez Anaconda, installez NumPy en accédant à votre terminal ou à l'invite de commandes (ou Anaconda Prompt) ou directement sur une cellule Jupyter Notebook (sans oublier de de redémarrer le noyau juste après) et tapez :**
    
    conda install numpy
    
ou

    pip install numpy

**Si vous ne possédez pas Anaconda et que vous ne pouvez pas l'installer, veuillez vous référer à la [documentation officielle de NumPy sur les différentes instructions d'installation.](https://www.scipy.org/install.html)**

_____

### Importation de NumPy

Une fois que vous avez installé NumPy, vous pouvez l'importer en tant que bibliothèque :

In [ ]:
import numpy as np

NumPy dispose de nombreuses fonctions et capacités intégrées. Nous ne les couvrirons pas tous, mais nous nous concentrerons plutôt sur certains des aspects les plus importants de NumPy : les vecteurs, les tableaux, les matrices et la génération de nombres. Commençons par discuter des tableaux.

## Tableaux NumPy

Les tableaux NumPy sont la principale façon d'utiliser NumPy tout au long du cours. Les tableaux NumPy se déclinent essentiellement en deux éléments : les vecteurs et les matrices. Les vecteurs sont des tableaux strictement unidimensionnels (1D) et les matrices sont 2D (mais il faut noter qu'une matrice peut toujours ne comporter qu'une seule ligne ou qu'une seule colonne).

#### Pourquoi utiliser un tableau NumPy ?

**Pourquoi ne pas simplement utiliser une liste ?**

Il existe de nombreuses raisons d'utiliser un tableau NumPy au lieu d'un objet de liste Python « standard ». Nos principales raisons sont les suivantes :
* Efficacité de la mémoire du « array NumPy » vs. « list »
* Élargissement facile aux objets N-dimensionnels
* Vitesse de calcul du tableau PumPy
* Opérations et fonctions de diffusion (broadcasting) avec NumPy
* Toutes les bibliothèques de Data Science et de Machine Learning que nous utilisons sont construites avec NumPy

#### Exemple simple d'un tableau NumPy

In [ ]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [ ]:
type(my_list)

list

In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
my_array

array([1, 2, 3])

Commençons notre introduction en explorant comment créer des tableaux NumPy.

## Création de tableaux NumPy à partir d'objets

### À partir d'une liste Python

Nous pouvons créer un tableau en convertissant directement une liste ou une liste de listes :

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Méthodes intégrées pour créer des tableaux

Il existe de nombreuses façons intégrées de générer des tableaux.

### arange

Retourner des valeurs uniformément espacées dans un intervalle donné. [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros et ones

Génère des tableaux de zéros ou de uns. [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Retourne des nombres uniformément espacés sur un intervalle spécifié. [[doc](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Notez que `.linspace()` **inclut** la valeur stop. Pour obtenir un tableau de fractions courantes, augmentez le nombre d'éléments :</font>

In [ ]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Crée une matrice identité [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
NumPy propose également de nombreux moyens de créer des tableaux de nombres aléatoires :


### rand
Crée un tableau de la forme donnée et le remplit d'échantillons aléatoires provenant d'une distribution uniforme sur les éléments suivants ``[0, 1)``. [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [ ]:
np.random.rand(2)

array([0.65548774, 0.8331804 ])

In [ ]:
np.random.rand(5,5)

array([[0.66573705, 0.66589354, 0.97749637, 0.30130292, 0.78928624],
       [0.57860863, 0.00500784, 0.80351377, 0.89788515, 0.88520001],
       [0.71991517, 0.52762686, 0.50653047, 0.7024826 , 0.6278918 ],
       [0.94759495, 0.0233678 , 0.08625033, 0.38751676, 0.0659804 ],
       [0.03952349, 0.98001028, 0.88222095, 0.98663453, 0.5565768 ]])

### randn

Retourne un échantillon (ou des échantillons) de la loi « normale standard » [σ = 1]. Contrairement à **rand** qui est uniforme, les valeurs proches de zéro sont plus susceptibles d'apparaître. [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [ ]:
np.random.randn(2)

array([-0.0119467 ,  0.97331799])

In [ ]:
np.random.randn(5,5)

array([[-0.49210121,  0.07059821, -1.58672556, -2.51723474, -1.06812987],
       [-0.51086659,  1.42923301, -1.03622043,  0.7509413 , -0.97294068],
       [ 0.72642467,  3.8357649 ,  0.70828499, -0.05976668, -0.47425165],
       [-0.24326423, -0.42189446,  0.56218621,  0.14307098,  0.91225367],
       [ 0.90111041,  1.30986756, -0.93366978, -1.27277723,  0.20447464]])

### randint
Retourne des nombres entiers aléatoires de `low` (inclusif) à `high` (exclusif).  [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [ ]:
np.random.randint(1,100)

24

In [ ]:
np.random.randint(1,100,10)

array([27, 24, 12, 22, 87, 29, 31, 74, 38, 53])

### seed
Peut être utilisé pour définir l'état aléatoire, de sorte que les mêmes résultats "aléatoires" puissent être reproduits. [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Attributs et méthodes Array


Examinons quelques attributs et méthodes utiles pour un tableau :

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Retourne un tableau contenant les mêmes données avec une nouvelle forme (ou dimension). [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## max, min, argmax, argmin

Ce sont des méthodes utiles pour trouver les valeurs maximales ou minimales. Ou pour trouver leurs emplacements d'index en utilisant argmin ou argmax

In [ ]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [ ]:
ranarr.max()

39

In [ ]:
ranarr.argmax()

7

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

9

## Shape

Shape est un attribut des tableaux (et non une méthode) :  [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [ ]:
# Vecteur
arr.shape

(25,)

In [ ]:
# Remarquez les deux sets de parenthèses
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

## dtype

Vous pouvez également saisir le type de données de l'objet dans le tableau : [[doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')